apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=main
            - --git-path=cluster
            - --git-user=sasumaki
            - --git-email=sasumaki@users.noreply.github.com
            - --git-url=git@github.com:sasumaki/asd