
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-system-client
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./client-installed
  prune: true
  dependsOn:
    - name: cluster-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
