apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mnist-
  namespace: argo
spec:
  # serviceAccountName: argo
  volumes:
  - name: ssh-key-volume
    secret:
      secretName: github-creds
      defaultMode: 256
  entrypoint: flow 
  templates:
  - name: flow
    steps:
      - - name: train
          template: training
          arguments:
            parameters:
              - name: lol
                value: beer
              - name: epochs
                value: "{{item.epochs}}"
              - name: learning_rate
                value: "{{item.rate}}"
          withItems:
            - { epochs: 3, rate: 0.0002 }

      - - name: git
          template: git-commit
          arguments:
            parameters:
            - name: S3_MODEL_URI
              value: "{{steps.train.outputs.parameters.S3_MODEL_URI}}"


  - name: training
    container:
      image: sasumaki/lol-train
      args: [aiga_train, Train, --parameters, "{{inputs.parameters}}"] 
    inputs:
      parameters:
        - name: lol
        - name: epochs
      artifacts:
      - name: data
        path: /app/data
        s3:
          endpoint: s3.amazonaws.com
          bucket: aiga-data
          key: MNIST_data
          accessKeySecret:
            name: aws-secret
            key: AWS_ACCESS_KEY_ID
          secretKeySecret:
            name: aws-secret
            key: AWS_SECRET_ACCESS_KEY
    outputs:
      parameters:
        - name: S3_MODEL_URI
          value: s3://aiga-models/{{pod.name}}
      artifacts:
      - name: model
        path: /app/outputs/model.onnx
        archive:
          none: {}
        s3:
          endpoint: s3.amazonaws.com
          bucket: aiga-models
          key: "{{pod.name}}/model.onnx"
          accessKeySecret:
            name: aws-secret
            key: AWS_ACCESS_KEY_ID
          secretKeySecret:
            name: aws-secret
            key: AWS_SECRET_ACCESS_KEY

      - name: metadata
        path: /app/outputs/metadata.yaml
        archive:
          none: {}
        s3:
          endpoint: s3.amazonaws.com
          bucket: aiga-models
          key: "{{pod.name}}/metadata.yaml"
          accessKeySecret:
            name: aws-secret
            key: AWS_ACCESS_KEY_ID
          secretKeySecret:
            name: aws-secret
            key: AWS_SECRET_ACCESS_KEY
    
  
  - name: git-commit
    inputs:
      parameters:
        - name: S3_MODEL_URI
      artifacts:
      - name: mnist-source
        path: /src
        git:
          repo: https://github.com/sasumaki/mnist.git
          depth: 1
          revision: staging
    script: 
      image: sasumaki/git:b
      command: [sh]
      volumeMounts:
      - name: ssh-key-volume
        mountPath: "/root/.ssh"
      source: |
        cd /src
        echo "MODEL_URI={{inputs.parameters.S3_MODEL_URI}}" > manifests/environment.properties
        cat manifests/environment.properties
        git config --global user.email "workflow-bot@example.com"
        git config --global user.name "Argo Workflows"
        git add -A
        git commit -m "bump model uri"

        ls -la /

        export GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa"
        git push git@github.com:sasumaki/mnist.git


